SUPABASE_URL = "https://zyoonimgezivevnxfqep.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5b29uaW1nZXppdmV2bnhmcWVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3OTkxNDYsImV4cCI6MjA3NDM3NTE0Nn0.ecZ4TMGsDHvAK02oP8P-IUWlpNOUmKEv8RUm-N1ClQQ"
